# Generated by Django 5.2.4 on 2025-09-11 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicaciones', '0002_publicacion_autor'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacion',
            name='tipo_publicacion',
            field=models.CharField(choices=[('venta', 'Venta'), ('servicio', 'Servicio'), ('busqueda', 'Búsqueda'), ('otro', 'Otro')], default='otro', max_length=10),
        ),
    ]
