# Generated by Django 5.2.4 on 2025-09-17 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicaciones', '0005_alter_publicacion_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacion',
            name='tipo_publicacion',
            field=models.CharField(choices=[('venta', '🛒 Venta'), ('servicio', '🔧 Servicio'), ('busqueda', '🔍 Búsqueda'), ('donacion', '🎁 Donación'), ('intercambio', '🔄 Intercambio'), ('evento', '📅 Evento'), ('recomendacion', '⭐ Recomendación'), ('otro', 'Otro')], default='otro', max_length=20),
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='titulo',
            field=models.CharField(max_length=200, verbose_name='Título'),
        ),
    ]
