# Generated by Django 5.2.4 on 2025-09-17 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicaciones', '0006_alter_publicacion_tipo_publicacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacion',
            name='estado',
            field=models.CharField(choices=[('activo', 'Activo'), ('vendido', 'Vendido'), ('completado', 'Completado'), ('cancelado', 'Cancelado'), ('oculto', 'Oculto')], default='activo', max_length=12, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='contenido',
            field=models.TextField(verbose_name='Contenido'),
        ),
    ]
