# Generated by Django 5.2.4 on 2025-09-17 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicaciones', '0007_publicacion_estado_alter_publicacion_contenido'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicacion',
            name='is_delete',
        ),
        migrations.AddField(
            model_name='publicacion',
            name='delete_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de eliminación'),
        ),
    ]
