# Generated by Django 5.2.4 on 2025-09-17 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicaciones', '0008_remove_publicacion_is_delete_publicacion_delete_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacion',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AddField(
            model_name='publicacion',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
