# Generated by Django 5.2.4 on 2025-09-17 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicaciones', '0009_publicacion_is_active_publicacion_updated_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publicacion',
            options={'ordering': ['-fecha_publicacion'], 'permissions': [('can_feature_post', 'Puede destacar publicaciones'), ('can_moderate_post', 'Puede moderar publicaciones')], 'verbose_name': 'Publicación', 'verbose_name_plural': 'Publicaciones'},
        ),
        migrations.AddField(
            model_name='publicacion',
            name='email_informes',
            field=models.EmailField(blank=True, help_text='Email de para solicitar información adicional', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='publicacion',
            name='telefono_informes',
            field=models.CharField(blank=True, help_text='Número de Teléfono para solicitar información adicional', max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='publicacion',
            name='whatsapp_informes',
            field=models.CharField(blank=True, help_text='Número de WhatsApp para solicitar información adicional', max_length=15, null=True),
        ),
    ]
