# Generated by Django 5.2.11 on 2026-03-15 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicaciones', '0011_alter_publicacion_autor'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacion',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
