# Generated by Django 5.2.11 on 2026-03-16 14:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicaciones', '0012_publicacion_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicacion',
            name='delete_at',
        ),
        migrations.AddField(
            model_name='publicacion',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='Fecha y hora en que el registro fue eliminado', null=True, verbose_name='Fecha de eliminación'),
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Última actualización'),
        ),
    ]
