# Generated by Django 5.2.4 on 2025-08-15 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mascotas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mascota',
            name='Unidad_habit',
        ),
    ]
