# Generated by Django 5.2.4 on 2025-08-25 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascotas', '0002_remove_mascota_unidad_habit'),
    ]

    operations = [
        migrations.AddField(
            model_name='mascota',
            name='nombre',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
