# Generated by Django 5.2.4 on 2025-09-11 18:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascotas', '0003_mascota_nombre'),
        ('unidades', '0008_alter_division_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='mascota',
            name='Unidad_habit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mascotas', to='unidades.unidad_habit'),
        ),
    ]
