# Generated by Django 5.1.4 on 2025-09-15 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascotas', '0004_mascota_unidad_habit'),
    ]

    operations = [
        migrations.AddField(
            model_name='mascota',
            name='color',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='mascota',
            name='foto',
            field=models.ImageField(blank=True, help_text='Foto de la mascota', null=True, upload_to='mascotas/', verbose_name='Foto'),
        ),
        migrations.AddField(
            model_name='mascota',
            name='tamaño',
            field=models.CharField(blank=True, choices=[('CH', 'Chico'), ('MD', 'Mediano'), ('GR', 'Grande')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
