# Generated by Django 5.1.4 on 2025-09-15 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mascotas', '0005_mascota_color_mascota_foto_mascota_tamaño_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mascota',
            options={'ordering': ['unidad_habit', 'tipo_mascota', 'nombre'], 'verbose_name': 'Mascota', 'verbose_name_plural': 'Mascotas'},
        ),
        migrations.RenameField(
            model_name='mascota',
            old_name='Unidad_habit',
            new_name='unidad_habit',
        ),
    ]
