# Generated by Django 5.1.4 on 2025-09-15 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascotas', '0006_alter_mascota_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mascota',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
