# Generated by Django 5.1.4 on 2025-09-15 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mascotas', '0007_mascota_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mascota',
            name='is_delete',
        ),
    ]
