# Generated by Django 5.1.4 on 2025-09-15 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascotas', '0008_remove_mascota_is_delete'),
    ]

    operations = [
        migrations.AddField(
            model_name='mascota',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de eliminación'),
        ),
    ]
