# Generated by Django 5.2.4 on 2025-09-16 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mascotas', '0009_mascota_deleted_at'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='mascota',
            table='mascotas',
        ),
    ]
