# Generated by Django 5.2.11 on 2026-03-15 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascotas', '0010_alter_mascota_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='Fecha y hora en que el registro fue eliminado', null=True, verbose_name='Fecha de eliminación'),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Última actualización'),
        ),
    ]
