# Generated by Django 5.2.11 on 2026-03-16 14:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascotas', '0011_alter_mascota_created_at_alter_mascota_deleted_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de creación'),
        ),
    ]
