# Generated by Django 5.1.4 on 2025-07-25 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reserva',
            old_name='delete',
            new_name='is_delete',
        ),
    ]
