# Generated by Django 5.2.4 on 2025-08-15 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0002_initial'),
    ]

    operations = [
        
        migrations.RemoveField(
            model_name='reserva',
            name='user',
        ),
    ]
