# Generated by Django 5.2.4 on 2025-08-25 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0003_remove_reserva_unidad_remove_reserva_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='fecha_reserva',
        ),
        migrations.AddField(
            model_name='reserva',
            name='fin_reserva',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reserva',
            name='inicio_reserva',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
