# Generated by Django 5.2.4 on 2025-09-11 18:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0005_reserva_user'),
        ('unidades', '0008_alter_division_unique_together'),
        ('zonas_sociales', '0003_zona_social_nombre_alter_zona_social_tipo_zona'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='unidad',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='unidades.unidad'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='zona_social',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='zonas_sociales.zona_social'),
        ),
    ]
