# Generated by Django 5.2.4 on 2025-09-11 18:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0006_reserva_unidad_reserva_zona_social'),
        ('unidades', '0008_alter_division_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='unidad_habit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='unidades.unidad_habit'),
        ),
    ]
