# Generated by Django 5.2.4 on 2025-09-11 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0008_reserva_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='motivo',
            field=models.TextField(blank=True, null=True),
        ),
    ]
