# Generated by Django 5.2.4 on 2025-09-11 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0009_reserva_motivo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reserva',
            old_name='fecha_creacion',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='reserva',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
