# Generated by Django 5.1.4 on 2025-09-16 20:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0010_rename_fecha_creacion_reserva_created_at_and_more'),
        ('zonas_sociales', '0007_alter_zona_social_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='zona_social',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='zonas_sociales.zona_social'),
        ),
    ]
