# Generated by Django 5.1.4 on 2025-09-16 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0011_alter_reserva_zona_social'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reserva',
            old_name='unidad',
            new_name='unidad_residencial',
        ),
    ]
