# Generated by Django 5.1.4 on 2025-09-16 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0012_rename_unidad_reserva_unidad_residencial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='numero_personas',
            field=models.IntegerField(blank=True, null=True, verbose_name='Número de Personas'),
        ),
    ]
