# Generated by Django 5.1.4 on 2025-09-16 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0013_reserva_numero_personas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='motivo',
            field=models.TextField(blank=True, null=True, verbose_name='Motivo de Reserva'),
        ),
    ]
