# Generated by Django 5.1.4 on 2025-09-16 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0014_alter_reserva_motivo'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='reserva',
            table='reservas_reserva',
        ),
    ]
