# Generated by Django 5.1.4 on 2025-09-16 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0015_alter_reserva_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reserva',
            options={'ordering': ['inicio_reserva'], 'verbose_name': 'Reserva', 'verbose_name_plural': 'Reservas'},
        ),
    ]
