# Generated by Django 5.2.4 on 2025-09-17 20:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0016_alter_reserva_options'),
        ('zonas_sociales', '0007_alter_zona_social_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='zona_social',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='zonas_sociales.zona_social'),
        ),
    ]
