# Generated by Django 5.2.11 on 2026-03-15 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0017_alter_reserva_zona_social'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='is_delete',
        ),
        migrations.AddField(
            model_name='reserva',
            name='delete_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de eliminación'),
        ),
    ]
