# Generated by Django 5.2.11 on 2026-03-16 14:53

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0018_remove_reserva_is_delete_reserva_delete_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='delete_at',
        ),
        migrations.AddField(
            model_name='reserva',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='Fecha y hora en que el registro fue eliminado', null=True, verbose_name='Fecha de eliminación'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='numero_personas',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Número de Personas'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Última actualización'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
