# Generated by Django 5.2.4 on 2025-08-15 21:56

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Unidad',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('nit', models.CharField(max_length=45)),
                ('direccion', models.CharField(max_length=200)),
                ('telefono', models.CharField(max_length=45)),
                ('tipo_unidad_habit', models.CharField(choices=[('A', 'Apartamento'), ('C', 'Casa')], max_length=4)),
                ('cantidad_unid_habit', models.IntegerField(blank=True, null=True)),
                ('link_registro', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_delete', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Unidad',
                'verbose_name_plural': 'Unidades',
                'db_table': 'unidad',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.AutoField(help_text='Identificador único Universal.', primary_key=True, serialize=False, verbose_name='ID único')),
                ('tipo_division', models.CharField(choices=[('TORRE', 'Torre'), ('EDIFICIO', 'Edificio'), ('MANZANA', 'Manzana'), ('BLOQUE', 'Bloque'), ('ETAPA', 'Etapa'), ('SECTOR', 'Sector')], default='TORRE', help_text='Tipo de agrupación arquitectónica (ej: Torre, Edificio, Manzana). Mantenga consistencia en la nomenclatura para todo el conjunto residencial.', max_length=20, verbose_name='Tipo de División')),
                ('identificador', models.CharField(default='1', help_text='Letra/numero que identifica la división (ej: 1, 2, A, B, ). Mantenga consistencia en la nomenclatura para todo el conjunto residencial.', max_length=10, validators=[django.core.validators.RegexValidator(message='Solo se permiten caracteres alfanuméricos (letras y números).', regex='^[a-zA-Z0-9]+$')], verbose_name='Identificador único')),
                ('nombre', models.CharField(default='', editable=False, help_text='Nombre o número de la división dentro de la unidad (ej: Torre A, Edificio 1, Manzana B). Mantenga consistencia en la nomenclatura para todo el conjunto residencial.', max_length=50, verbose_name='Nombre completo de la División')),
                ('cantidad_pisos', models.PositiveIntegerField(blank=True, help_text='Cantidad de pisos que tiene la división. Si no aplica, dejar en blanco.', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(150)], verbose_name='Cantidad de Pisos')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('unidad', models.ForeignKey(help_text='Unidad residencial a la que pertenece esta división.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='divisiones', to='unidades.unidad', verbose_name='Unidad Residencial')),
            ],
            options={
                'verbose_name': 'Division',
                'verbose_name_plural': 'Divisiones',
                'db_table': 'divisiones',
                'ordering': ['unidad', 'tipo_division', 'identificador'],
            },
        ),
        migrations.CreateModel(
            name='Unidad_habit',
            fields=[
                ('id', models.CharField(editable=False, help_text='ID generado automáticamente como Piso+Número+Torre (ej: 401A)', max_length=20, primary_key=True, serialize=False)),
                ('cant_habitantes', models.IntegerField(default=1)),
                ('piso', models.CharField(default='0', help_text='Número del piso donde se encuentra la unidad habitacional (ej: 1, 2, 3)', max_length=2)),
                ('numero', models.CharField(default='01', help_text='Número de la unidad habitacional dentro del piso (ej: 01, 02, 03)', max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('division', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unidades_habitacionales', to='unidades.division')),
                ('unidad', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='unidades.unidad')),
            ],
        ),
        migrations.AddConstraint(
            model_name='division',
            constraint=models.UniqueConstraint(fields=('unidad', 'nombre'), name='unique_nombre_por_unidad'),
        ),
        migrations.AlterUniqueTogether(
            name='division',
            unique_together={('unidad', 'tipo_division', 'identificador')},
        ),
    ]
