# Generated by Django 5.1.4 on 2025-07-21 21:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_division', models.CharField(max_length=50)),
                ('cant_unidades_habit', models.SmallIntegerField(blank=True, null=True)),
                ('cant_pisos', models.IntegerField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('delete', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Division',
                'verbose_name_plural': 'Divisiones',
                'db_table': 'division',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Unidad',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('nit', models.CharField(max_length=45)),
                ('direccion', models.CharField(max_length=200)),
                ('telefono', models.CharField(max_length=45)),
                ('tipo_unidad_habit', models.CharField(choices=[('A', 'Apartamento'), ('C', 'Casa')], max_length=4)),
                ('cantidad_unid_habit', models.IntegerField(blank=True, null=True)),
                ('link_registro', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('delete', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Unidad',
                'verbose_name_plural': 'Unidades',
                'db_table': 'unidad',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Unidad_habit',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('cant_habitantes', models.IntegerField(default=1)),
                ('numero_unidad_habit', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('delete', models.BooleanField(default=False)),
                ('division', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='unidades.division')),
                ('unidad', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='unidades.unidad')),
            ],
        ),
    ]
