# Generated by Django 5.2.4 on 2025-09-04 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unidades', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unidad_habit',
            name='cant_habitantes',
            field=models.IntegerField(default=0),
        ),
    ]
