# Generated by Django 5.1.4 on 2025-07-25 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unidades', '0002_remove_division_cant_unidades_habit_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='division',
            old_name='delete',
            new_name='is_delete',
        ),
    ]
