# Generated by Django 5.1.4 on 2024-12-06 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unidades', '0002_user_created_at_user_deleted_at_user_telefono_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unidad',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('nit', models.CharField(max_length=45)),
                ('direccion', models.CharField(max_length=200)),
                ('telefono', models.CharField(max_length=45)),
                ('tipo_unidad_habit', models.CharField(choices=[('A', 'Apartamento'), ('C', 'Casa')], max_length=4)),
                ('cantidad_unid_habit', models.IntegerField(blank=True, null=True)),
                ('link_registro', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('delete', models.BooleanField(default=False)),
            ],
        ),
    ]
