# Generated by Django 5.2.4 on 2025-09-04 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unidades', '0002_alter_unidad_habit_cant_habitantes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unidad_habit',
            name='cant_habitantes',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
