# Generated by Django 5.1.4 on 2025-07-25 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unidades', '0003_rename_delete_division_is_delete'),
    ]

    operations = [
        migrations.RenameField(
            model_name='unidad',
            old_name='delete',
            new_name='is_delete',
        ),
        migrations.RenameField(
            model_name='unidad_habit',
            old_name='delete',
            new_name='is_delete',
        ),
    ]
