# Generated by Django 5.2.4 on 2025-09-04 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unidades', '0003_alter_unidad_habit_cant_habitantes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unidad_habit',
            name='piso',
            field=models.CharField(blank=True, default='00', help_text='Número del piso donde se encuentra la unidad habitacional (ej: 1, 2, 3)', max_length=2, null=True),
        ),
    ]
