# Generated by Django 5.1.4 on 2024-12-06 21:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unidades', '0003_unidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='unidad',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='unidades.unidad'),
        ),
        migrations.AlterField(
            model_name='user',
            name='deleted_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
