# Generated by Django 5.1.4 on 2024-12-12 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unidades', '0004_user_unidad_alter_user_deleted_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_division', models.CharField(max_length=50)),
                ('cant_unidades_habit', models.SmallIntegerField(blank=True, null=True)),
                ('cant_pisos', models.IntegerField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('delete', models.BooleanField(default=False)),
            ],
        ),
    ]
