# Generated by Django 5.1.4 on 2025-07-25 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unidades', '0004_rename_delete_unidad_is_delete_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unidad_habit',
            name='numero_unidad_habit',
        ),
    ]
