# Generated by Django 5.2.4 on 2025-09-04 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unidades', '0004_alter_unidad_habit_piso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unidad_habit',
            name='piso',
            field=models.CharField(blank=True, help_text='Número del piso donde se encuentra la unidad habitacional (ej: 1, 2, 3)', max_length=2, null=True),
        ),
    ]
