# Generated by Django 5.2.4 on 2025-07-27 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unidades', '0005_remove_unidad_habit_numero_unidad_habit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='division',
            name='id',
            field=models.CharField(help_text='Identificador único de la torre/edificio/ manzana. Puede ser letra (A, B) ó número (1, 2, 3)', max_length=6, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='unidad_habit',
            name='id',
            field=models.CharField(editable=False, max_length=10, primary_key=True, serialize=False),
        ),
    ]
