# Generated by Django 5.1.4 on 2024-12-12 21:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unidades', '0005_division'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unidad_habit',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('cant_habitantes', models.IntegerField(default=1)),
                ('numero_unidad_habit', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('delete', models.BooleanField(default=False)),
                ('division', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='unidades.division')),
                ('unidad', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='unidades.unidad')),
            ],
        ),
    ]
