# Generated by Django 5.2.4 on 2025-09-04 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unidades', '0006_alter_division_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='division',
            options={'ordering': ['unidad', 'nombre'], 'verbose_name': 'Division', 'verbose_name_plural': 'Divisiones'},
        ),
    ]
