# Generated by Django 5.2.4 on 2025-07-27 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unidades', '0006_alter_division_id_alter_unidad_habit_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='division',
            name='nombre_division',
            field=models.CharField(help_text='Tipo de división dentro de la Unidad Residencial donde se encuentran las unidades habitacionales, como: torre/edificio/ manzana', max_length=50),
        ),
    ]
