# Generated by Django 5.1.4 on 2024-12-12 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unidades', '0006_unidad_habit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('numero_dcto', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_dcto', models.CharField(choices=[('CC', 'Cédula ciudadanía'), ('CE', 'Cédula extranjería'), ('P', 'Pasaporte'), ('PT', 'Permiso de trabajo'), ('O', 'Otro')], max_length=4)),
            ],
        ),
    ]
