# Generated by Django 5.1.4 on 2024-12-13 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unidades', '0007_documento'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Unidad_habit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='unidades.unidad_habit'),
        ),
    ]
