# Generated by Django 5.2.4 on 2025-07-27 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unidades', '0007_alter_division_nombre_division'),
    ]

    operations = [
        migrations.AddField(
            model_name='unidad_habit',
            name='numero',
            field=models.CharField(default='01', help_text='Número de la unidad habitacional dentro del piso (ej: 01, 02, 03)', max_length=2),
        ),
        migrations.AddField(
            model_name='unidad_habit',
            name='piso',
            field=models.CharField(default='00', help_text='Número del piso donde se encuentra la unidad habitacional (ej: 1, 2, 3)', max_length=2),
        ),
        migrations.AlterField(
            model_name='division',
            name='nombre_division',
            field=models.CharField(help_text='Tipo de agrupación arquitectónica (ej: Torre, Edificio, Manzana). Mantenga consistencia en la nomenclatura para todo el conjunto residencial.', max_length=50),
        ),
        migrations.AlterField(
            model_name='unidad_habit',
            name='id',
            field=models.CharField(editable=False, help_text='ID generado automáticamente como Piso+Número+Torre (ej: 401A)', max_length=10, primary_key=True, serialize=False),
        ),
    ]
