# Generated by Django 5.2.4 on 2025-09-04 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unidades', '0007_alter_division_options'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='division',
            unique_together={('unidad', 'nombre')},
        ),
    ]
