# Generated by Django 5.1.4 on 2024-12-13 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unidades', '0008_user_unidad_habit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='Unidad_habit',
            new_name='unidad_habit',
        ),
        migrations.AddField(
            model_name='user',
            name='documento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='unidades.documento'),
        ),
    ]
