# Generated by Django 5.2.4 on 2025-07-27 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unidades', '0008_unidad_habit_numero_unidad_habit_piso_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unidad_habit',
            name='piso',
            field=models.CharField(default='0', help_text='Número del piso donde se encuentra la unidad habitacional (ej: 1, 2, 3)', max_length=2),
        ),
    ]
