# Generated by Django 5.2.4 on 2025-09-11 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unidades', '0008_alter_division_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='unidad',
            options={'ordering': ['id'], 'verbose_name': 'Unidad_Residencial', 'verbose_name_plural': 'Unidades'},
        ),
    ]
