# Generated by Django 5.2.4 on 2025-09-11 20:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unidades', '0009_alter_unidad_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unidad',
            name='nit',
            field=models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='El NIT debe tener el formato: 123456789-0', regex='^[0-9]{9}-[0-9]$')], verbose_name='NIT'),
        ),
    ]
