# Generated by Django 5.1.4 on 2024-12-13 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unidades', '0009_rename_unidad_habit_user_unidad_habit_user_documento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('placa', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('numero', models.IntegerField(null=True)),
                ('marca', models.CharField(blank=True, max_length=50, null=True)),
                ('color', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('delete', models.BooleanField(default=False)),
                ('unidad_habit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='unidades.unidad_habit')),
            ],
        ),
    ]
