# Generated by Django 5.1.4 on 2024-12-13 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unidades', '0010_vehiculo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehiculo',
            name='numero',
        ),
    ]
