# Generated by Django 5.2.4 on 2025-07-27 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unidades', '0010_alter_unidad_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unidad',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
