# Generated by Django 5.2.4 on 2025-09-11 20:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unidades', '0011_alter_unidad_nit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unidad',
            name='telefono',
            field=models.CharField(help_text='Teléfono principal de contacto  de la administración.', max_length=45, validators=[django.core.validators.RegexValidator(message='El teléfono debe tener entre 7 y 15 dígitos. Puede incluir + al inicio.', regex='^\\+?[0-9]{7,15}$')]),
        ),
    ]
