# Generated by Django 5.2.4 on 2025-07-27 15:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unidades', '0011_alter_unidad_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='division',
            name='unidad',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='unidades.unidad'),
        ),
    ]
