# Generated by Django 5.1.4 on 2024-12-13 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unidades', '0011_remove_vehiculo_numero'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parqueadero',
            fields=[
                ('numero', models.IntegerField(primary_key=True, serialize=False)),
                ('unidad_habit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='unidades.unidad_habit')),
            ],
        ),
    ]
