# Generated by Django 5.1.4 on 2024-12-13 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unidades', '0012_parqueadero'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculo',
            name='parqueadero',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='unidades.parqueadero'),
        ),
    ]
