# Generated by Django 5.2.4 on 2025-07-27 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unidades', '0012_division_unidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='unidad',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
