# Generated by Django 5.2.4 on 2025-09-11 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unidades', '0012_alter_unidad_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unidad',
            name='nombre',
            field=models.CharField(max_length=100, unique=True, verbose_name='Nombre de la unidad Residencial'),
        ),
    ]
