# Generated by Django 5.2.4 on 2025-09-11 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unidades', '0013_alter_unidad_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unidad',
            name='link_registro',
            field=models.URLField(blank=True, help_text='Enlace para el registro de nuevos usuarios.', max_length=300, null=True),
        ),
    ]
