# Generated by Django 5.1.4 on 2024-12-13 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unidades', '0013_vehiculo_parqueadero'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_masc', models.CharField(choices=[('P', 'Perro'), ('G', 'Gato')], max_length=4)),
                ('raza', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('delete', models.BooleanField(default=False)),
                ('Unidad_habit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='unidades.unidad_habit')),
            ],
        ),
    ]
