# Generated by Django 5.2.4 on 2025-07-28 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unidades', '0013_unidad_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='division',
            name='numero_division',
            field=models.CharField(default='00', help_text='Número, letra, o clasificación de la división dentro de la unidad (ej: 1, 2, 3 ó A, B, C). Mantenga consistencia en la nomenclatura para todo el conjunto residencial.', max_length=5),
        ),
        migrations.AlterField(
            model_name='division',
            name='id',
            field=models.CharField(editable=False, help_text='Formado por: [ID Unidad]-[ID División]', max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='division',
            name='nombre_division',
            field=models.CharField(default='00', help_text='Tipo de agrupación arquitectónica (ej: Torre, Edificio, Manzana). Mantenga consistencia en la nomenclatura para todo el conjunto residencial.', max_length=50),
        ),
    ]
