# Generated by Django 5.2.4 on 2025-07-28 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unidades', '0014_division_numero_division_alter_division_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='division',
            name='nombre_division',
            field=models.CharField(default='Torre', help_text='Tipo de agrupación arquitectónica (ej: Torre, Edificio, Manzana). Mantenga consistencia en la nomenclatura para todo el conjunto residencial.', max_length=50),
        ),
    ]
