# Generated by Django 5.2.4 on 2025-09-11 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unidades', '0014_alter_unidad_link_registro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unidad',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación'),
        ),
    ]
