# Generated by Django 5.1.4 on 2025-09-12 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unidades', '0015_alter_unidad_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unidad',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Última actualización'),
        ),
    ]
