# Generated by Django 5.2.4 on 2025-07-28 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unidades', '0015_alter_division_nombre_division'),
    ]

    operations = [
        migrations.AlterField(
            model_name='division',
            name='numero_division',
            field=models.CharField(default='1', help_text='Número, letra, o clasificación de la división dentro de la unidad (ej: 1, 2, 3 ó A, B, C). Mantenga consistencia en la nomenclatura para todo el conjunto residencial.', max_length=5),
        ),
    ]
