# Generated by Django 5.1.4 on 2025-09-12 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unidades', '0016_alter_unidad_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unidad',
            name='direccion',
            field=models.CharField(help_text='Dirección completa incluyendo ciudad y barrio', max_length=200, verbose_name='Dirección completa'),
        ),
    ]
