# Generated by Django 5.1.4 on 2025-09-12 14:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unidades', '0017_alter_unidad_direccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='unidad',
            name='email',
            field=models.EmailField(blank=True, help_text='Correo electrónico de contacto de la administración.', max_length=254, null=True, unique=True, verbose_name='Correo electrónico de contacto'),
        ),
        migrations.AlterField(
            model_name='unidad',
            name='telefono',
            field=models.CharField(help_text='Teléfono principal de contacto  de la administración.', max_length=45, validators=[django.core.validators.RegexValidator(message='El teléfono debe tener entre 7 y 15 dígitos. Puede incluir + al inicio.', regex='^\\+?[0-9]{7,15}$')], verbose_name='Teléfono de contacto'),
        ),
        migrations.AlterField(
            model_name='unidad',
            name='tipo_unidad_habit',
            field=models.CharField(choices=[('A', 'Apartamento'), ('C', 'Casa'), ('M', 'Mixto (Apartamentos y Casas)'), ('O', 'Otro')], help_text='Tipo predominante de viviendas en la unidad residencial', max_length=1, verbose_name='Tipo de Unidades Habitacionales'),
        ),
    ]
