# Generated by Django 5.2.4 on 2025-07-28 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unidades', '0017_alter_division_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='division',
            name='id',
            field=models.CharField(editable=False, help_text='Formado por: [ID Unidad]-[ID División]', max_length=10, primary_key=True, serialize=False),
        ),
    ]
