# Generated by Django 5.1.4 on 2025-09-12 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unidades', '0018_unidad_email_alter_unidad_telefono_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unidad',
            name='nombre',
            field=models.CharField(help_text='Nombre oficial de la unidad residencial (ej: Conjunto Residencial Capriani)', max_length=100, unique=True, verbose_name='Nombre de la unidad Residencial'),
        ),
    ]
