# Generated by Django 5.1.4 on 2025-09-12 14:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unidades', '0019_alter_unidad_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='unidad',
            name='logo',
            field=models.ImageField(blank=True, help_text='Logo de la unidad residencial.', max_length=200, null=True, upload_to='logos/'),
        ),
        migrations.AlterField(
            model_name='unidad',
            name='nit',
            field=models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='El NIT debe tener el formato: 123456789-0', regex='^[0-9]{9}-[0-9]$')], verbose_name='NIT'),
        ),
    ]
