# Generated by Django 5.2.4 on 2025-07-29 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unidades', '0019_alter_division_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unidad_habit',
            name='id',
            field=models.CharField(editable=False, help_text='ID generado automáticamente como Piso+Número+Torre (ej: 401A)', max_length=20, primary_key=True, serialize=False),
        ),
    ]
