# Generated by Django 5.1.4 on 2025-09-12 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unidades', '0020_unidad_logo_alter_unidad_nit'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='unidad',
            options={'ordering': ['nombre'], 'verbose_name': 'Unidad_Residencial', 'verbose_name_plural': 'Unidades Residenciales'},
        ),
        migrations.AlterField(
            model_name='unidad',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterModelTable(
            name='unidad',
            table='unidades_residenciales',
        ),
    ]
