# Generated by Django 5.1.4 on 2025-09-12 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unidades', '0021_alter_unidad_options_alter_unidad_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unidad',
            name='is_delete',
        ),
        migrations.AddIndex(
            model_name='unidad',
            index=models.Index(fields=['nombre'], name='unidades_re_nombre_0e94d5_idx'),
        ),
        migrations.AddIndex(
            model_name='unidad',
            index=models.Index(fields=['nit'], name='unidades_re_nit_459912_idx'),
        ),
        migrations.AddIndex(
            model_name='unidad',
            index=models.Index(fields=['is_active'], name='unidades_re_is_acti_761ea1_idx'),
        ),
    ]
