# Generated by Django 5.1.4 on 2025-09-12 16:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unidades', '0022_remove_unidad_is_delete_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='division',
            name='tipo_division',
            field=models.CharField(choices=[('TORRE', 'Torre'), ('EDIFICIO', 'Edificio'), ('MANZANA', 'Manzana'), ('BLOQUE', 'Bloque'), ('ETAPA', 'Etapa'), ('SECTOR', 'Sector'), ('ZONA', 'Zona'), ('LOTE', 'Lote')], default='TORRE', help_text='Tipo de agrupación arquitectónica (ej: Torre, Edificio, Manzana). Mantenga consistencia en la nomenclatura para todo el conjunto residencial.', max_length=20, verbose_name='Tipo de División'),
        ),
        migrations.AlterField(
            model_name='division',
            name='unidad',
            field=models.ForeignKey(help_text='Unidad residencial a la que pertenece esta división.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='divisiones', to='unidades.unidad', verbose_name='Unidad Residencial'),
        ),
    ]
