# Generated by Django 5.1.4 on 2025-09-12 16:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unidades', '0023_alter_division_tipo_division_alter_division_unidad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='division',
            name='is_delete',
        ),
        migrations.AddField(
            model_name='division',
            name='delete_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de eliminación'),
        ),
        migrations.AddField(
            model_name='division',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='division',
            name='cantidad_pisos',
            field=models.PositiveIntegerField(blank=True, help_text='Cantidad de pisos que tiene la división. Obligatorio para Torres y Edificios.', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(150)], verbose_name='Cantidad de Pisos'),
        ),
        migrations.AlterField(
            model_name='division',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='division',
            name='nombre',
            field=models.CharField(default='', editable=False, help_text='Nombre o número de la división dentro de la unidad (ej: Torre A, Edificio 1, Manzana B). Mantenga consistencia en la nomenclatura para todo el conjunto residencial.', max_length=100, verbose_name='Nombre completo de la División'),
        ),
        migrations.AlterField(
            model_name='division',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Última actualización'),
        ),
    ]
