# Generated by Django 5.1.4 on 2025-09-12 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unidades', '0024_remove_division_is_delete_division_delete_at_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='division',
            unique_together=set(),
        ),
    ]
