# Generated by Django 5.1.4 on 2025-09-12 20:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unidades', '0025_alter_division_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unidad_habit',
            name='numero',
            field=models.CharField(default='01', help_text='Número de la unidad habitacional dentro del piso (ej: 01, 02, 03)', max_length=2, validators=[django.core.validators.RegexValidator(message='El número debe ser numérico (ej: 01, 02) o alfanumérico (ej: 01A, 02B)', regex='^[0-9]{1,3}[A-Z]?$')]),
        ),
        migrations.AlterField(
            model_name='unidad_habit',
            name='piso',
            field=models.CharField(blank=True, help_text='Número del piso donde se encuentra la unidad habitacional (ej: 1, 2, 3)', max_length=2, null=True, validators=[django.core.validators.RegexValidator(message='El piso debe ser un número de 1 o 2 dígitos (ej: 1, 2, ..., 10, 11, ..., 20).', regex='^[0-9]{1,2}$')]),
        ),
    ]
