# Generated by Django 5.1.4 on 2025-09-12 20:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unidades', '0026_alter_unidad_habit_numero_alter_unidad_habit_piso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unidad_habit',
            name='cant_habitantes',
            field=models.PositiveIntegerField(blank=True, help_text='Número total de personas que residen en esta unidad habitacional', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(50)], verbose_name='Cantidad de habitantes'),
        ),
        migrations.AlterField(
            model_name='unidad_habit',
            name='id',
            field=models.CharField(editable=False, help_text='ID generado automáticamente como Piso+Número+División (ej: 401A)', max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='unidad_habit',
            name='numero',
            field=models.CharField(help_text='Número de la unidad dentro del piso (ej: 01, 02, 03, 101A)', max_length=2, validators=[django.core.validators.RegexValidator(message='El número debe ser numérico (ej: 01, 02) o alfanumérico (ej: 01A, 02B)', regex='^[0-9]{1,3}[A-Z]?$')], verbose_name='Número de Unidad'),
        ),
        migrations.AlterField(
            model_name='unidad_habit',
            name='piso',
            field=models.CharField(blank=True, help_text='Número del piso donde se encuentra la unidad habitacional (ej: 1, 2, 3)', max_length=2, null=True, validators=[django.core.validators.RegexValidator(message='El piso debe ser un número de 1 o 2 dígitos (ej: 1, 2, ..., 10, 11, ..., 20).', regex='^[0-9]{1,2}$')], verbose_name='Piso'),
        ),
    ]
