# Generated by Django 5.1.4 on 2025-09-12 20:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unidades', '0027_alter_unidad_habit_cant_habitantes_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='unidad_habit',
            options={'ordering': ['unidad', 'id'], 'verbose_name': 'Unidad Habitacional', 'verbose_name_plural': 'Unidades Habitacionales'},
        ),
        migrations.RemoveField(
            model_name='unidad_habit',
            name='is_delete',
        ),
        migrations.AddField(
            model_name='unidad_habit',
            name='deleted_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de eliminación'),
        ),
        migrations.AddField(
            model_name='unidad_habit',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='unidad_habit',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='unidad_habit',
            name='division',
            field=models.ForeignKey(help_text='División (ej: Torre, Edificio) dentro de la unidad residencial donde se encuentra esta unidad habitacional.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='unidades_habitacionales', to='unidades.division', verbose_name='División'),
        ),
        migrations.AlterField(
            model_name='unidad_habit',
            name='unidad',
            field=models.ForeignKey(help_text='Unidad residencial a la que pertenece esta unidad habitacional.', on_delete=django.db.models.deletion.CASCADE, related_name='unidades_habitacionales', to='unidades.unidad', verbose_name='Unidad Residencial'),
        ),
        migrations.AlterField(
            model_name='unidad_habit',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Última actualización'),
        ),
        migrations.AddConstraint(
            model_name='unidad_habit',
            constraint=models.UniqueConstraint(fields=('unidad', 'piso', 'numero', 'division'), name='unique_unidad_habitacional_por_unidad', violation_error_message='Ya existe una unidad habitacional con este piso, número y división en la unidad residencial.'),
        ),
    ]
