# Generated by Django 5.1.4 on 2025-09-15 16:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unidades', '0028_alter_unidad_habit_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='division',
            name='delete_at',
        ),
        migrations.AddField(
            model_name='division',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='Fecha y hora en que el registro fue eliminado', null=True, verbose_name='Fecha de eliminación'),
        ),
        migrations.AddField(
            model_name='unidad',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='Fecha y hora en que el registro fue eliminado', null=True, verbose_name='Fecha de eliminación'),
        ),
        migrations.AlterField(
            model_name='unidad_habit',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='Fecha y hora en que el registro fue eliminado', null=True, verbose_name='Fecha de eliminación'),
        ),
        migrations.AlterField(
            model_name='unidad_habit',
            name='unidad',
            field=models.ForeignKey(help_text='Unidad residencial a la que pertenece esta unidad habitacional.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='unidades_habitacionales', to='unidades.unidad', verbose_name='Unidad Residencial'),
        ),
    ]
