# Generated by Django 5.1.4 on 2025-09-15 16:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unidades', '0029_remove_division_delete_at_division_deleted_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='unidad_habit',
            name='estado',
            field=models.CharField(choices=[('OCUPADO', 'Ocupado'), ('DISPONIBLE', 'Disponible'), ('MANTENIMIENTO', 'En Mantenimiento')], default='DISPONIBLE', help_text='Estado actual de la unidad habitacional', max_length=15, verbose_name='Estado de la Unidad Habitacional'),
        ),
        migrations.AlterField(
            model_name='unidad_habit',
            name='cant_habitantes',
            field=models.PositiveIntegerField(blank=True, help_text='Número total de personas que residen en esta unidad habitacional', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(8)], verbose_name='Cantidad de habitantes'),
        ),
    ]
