# Generated by Django 5.2.4 on 2025-09-16 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unidades', '0030_unidad_habit_estado_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='unidad_habit',
            table='unidades_habitacionales',
        ),
    ]
