# Generated by Django 5.2.11 on 2026-03-13 13:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unidades', '0031_alter_unidad_habit_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='division',
            name='cantidad_pisos',
            field=models.PositiveIntegerField(blank=True, help_text='Cantidad de pisos que tiene la división. Obligatorio para Torres y Edificios.', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(40)], verbose_name='Cantidad de Pisos'),
        ),
    ]
