# Generated by Django 5.2.11 on 2026-03-15 22:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unidades', '0033_alter_unidad_habit_piso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unidad_habit',
            name='piso',
            field=models.CharField(blank=True, help_text='Número del piso donde se encuentra la unidad habitacional (ej: 1, 2, 3)', max_length=2, null=True, validators=[django.core.validators.RegexValidator(message='El piso debe ser un número de 1 o 2 dígitos (ej: 1, 2, ..., 10, 11, ..., 20).', regex='^[0-9]{1,2}$')], verbose_name='Piso'),
        ),
    ]
