# Generated by Django 5.2.11 on 2026-03-17 20:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unidades', '0035_alter_division_created_at_alter_unidad_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unidad',
            name='nit',
            field=models.CharField(max_length=12, unique=True, validators=[django.core.validators.RegexValidator(message='El NIT debe tener el formato: 123456789-0 (8-10 dígitos, guión, dígito de verificación)', regex='^\\d{8,10}-\\d$')], verbose_name='NIT'),
        ),
    ]
