# Generated by Django 5.2.4 on 2025-09-17 15:00

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parqueaderos', '0001_initial'),
        ('unidades', '0031_alter_unidad_habit_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('placa', models.CharField(help_text='Formato: ABC123, ABC12D o AB1234', max_length=10, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(message='Formato de placa inválido. Use: ABC123, ABC12D o AB1234', regex='^[A-Z]{3}[0-9]{3}$|^[A-Z]{3}[0-9]{2}[A-Z]$|^[A-Z]{2}[0-9]{4}$')])),
                ('tipo', models.CharField(choices=[('CARRO', 'Carro'), ('MOTO', 'Moto'), ('CAMIONETA', 'Camioneta'), ('OTRO', 'Otro')], default='CARRO', max_length=10, verbose_name='Tipo de Vehículo')),
                ('marca', models.CharField(blank=True, max_length=50, null=True)),
                ('color', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Fecha y hora en que el registro fue eliminado', null=True, verbose_name='Fecha de eliminación')),
                ('parqueadero_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='parqueaderos.parqueadero')),
                ('unidad_habit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='unidades.unidad_habit')),
            ],
            options={
                'verbose_name': 'Vehículo',
                'verbose_name_plural': 'Vehículos',
                'db_table': 'vehiculos_vehiculo',
                'ordering': ['unidad_habit', 'placa'],
                'unique_together': {('placa', 'unidad_habit')},
            },
        ),
    ]
