# Generated by Django 5.1.4 on 2025-07-21 21:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parqueaderos', '0001_initial'),
        ('unidades', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('placa', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('marca', models.CharField(blank=True, max_length=50, null=True)),
                ('color', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('delete', models.BooleanField(default=False)),
                ('parqueadero', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='parqueaderos.parqueadero')),
                ('unidad_habit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='unidades.unidad_habit')),
            ],
            options={
                'verbose_name': 'Vehículo',
                'verbose_name_plural': 'Vehículos',
                'db_table': 'vehiculo',
                'ordering': ['placa'],
                'unique_together': {('placa', 'unidad_habit')},
            },
        ),
    ]
