# Generated by Django 5.2.4 on 2025-09-17 20:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parqueaderos', '0001_initial'),
        ('unidades', '0031_alter_unidad_habit_table'),
        ('vehiculos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='parqueadero_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehiculos', to='parqueaderos.parqueadero'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='unidad_habit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehiculos', to='unidades.unidad_habit'),
        ),
    ]
