# Generated by Django 5.2.11 on 2026-03-15 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0002_alter_vehiculo_parqueadero_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculo',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Última actualización'),
        ),
    ]
