# Generated by Django 5.2.11 on 2026-03-16 14:53

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unidades', '0035_alter_division_created_at_alter_unidad_created_at_and_more'),
        ('vehiculos', '0003_vehiculo_is_active_alter_vehiculo_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='unidad_habit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vehiculos', to='unidades.unidad_habit'),
        ),
    ]
