# Generated by Django 5.1.4 on 2025-09-15 19:29

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('unidades', '0030_unidad_habit_estado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('numero_dcto', models.CharField(max_length=20, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='El documento debe contener entre 5 y 20 caracteres alfanuméricos o guiones.', regex='^[0-9a-zA-Z-]{5,20}$')], verbose_name='Número de documento')),
                ('tipo_dcto', models.CharField(choices=[('CC', 'Cédula ciudadanía'), ('CE', 'Cédula extranjería'), ('PP', 'Pasaporte'), ('PT', 'Permiso de trabajo'), ('O', 'Otro')], default='CC', max_length=4)),
                ('genero', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro'), ('ND', 'Prefiero no decirlo')], max_length=2, null=True, verbose_name='Género')),
                ('fecha_nacimiento', models.DateField(blank=True, null=True, verbose_name='Fecha de nacimiento')),
                ('telefono', models.CharField(blank=True, max_length=45, null=True, validators=[django.core.validators.RegexValidator(message='El teléfono debe tener entre 7 y 15 dígitos. Puede incluir + al inicio.', regex='^\\+?[0-9]{7,15}$')], verbose_name='Teléfono')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('tipo_user', models.CharField(choices=[('AD', 'administrador'), ('IN', 'inquilino'), ('PR', 'propietario-residente'), ('PN', 'propietario-no-residente')], default='A', max_length=45)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Fecha y hora en que el registro fue eliminado', null=True, verbose_name='Fecha de eliminación')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('unidad_habit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuarios', to='unidades.unidad_habit')),
                ('unidad_residencial', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuarios', to='unidades.unidad')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'ordering': ['unidad_residencial', 'first_name', 'last_name'],
                'constraints': [models.UniqueConstraint(fields=('first_name', 'numero_dcto'), name='unique_documento_por_unidad', violation_error_message='Ya existe un usuario con este documento en la unidad residencial.')],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
