# Generated by Django 5.1.4 on 2025-07-25 18:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='documento',
            name='numero_dcto',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, unique=True, verbose_name='Número de documento'),
        ),
        migrations.AlterField(
            model_name='user',
            name='documento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='usuarios.documento'),
        ),
    ]
