# Generated by Django 5.2.4 on 2025-09-16 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='usuarios',
        ),
    ]
