# Generated by Django 5.1.4 on 2025-07-25 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_user_deleted_alter_documento_numero_dcto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='delete',
            field=models.BooleanField(default=False),
        ),
    ]
