# Generated by Django 5.2.11 on 2026-03-15 22:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('unidades', '0034_alter_unidad_habit_piso'),
        ('usuarios', '0002_alter_user_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='update_at',
        ),
        migrations.AddField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Última actualización'),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='usuario_set', related_query_name='usuario', to='auth.group'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active'),
        ),
        migrations.AlterField(
            model_name='user',
            name='unidad_habit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='residentes', to='unidades.unidad_habit'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, related_name='usuario_set', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
