# Generated by Django 5.1.4 on 2025-07-25 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_documento_delete'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documento',
            old_name='delete',
            new_name='is_delete',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='deleted',
            new_name='is_deleted',
        ),
    ]
