# Generated by Django 5.2.4 on 2025-07-28 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_rename_delete_documento_is_delete_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='tipo_user',
            field=models.CharField(choices=[('A', 'administrador'), ('I', 'inquilino'), ('P', 'propietario')], default='A', max_length=45),
        ),
    ]
