# Generated by Django 5.1.4 on 2025-07-21 21:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('unidades', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parqueadero',
            fields=[
                ('numero', models.IntegerField(primary_key=True, serialize=False)),
                ('unidad_habit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unidades.unidad_habit')),
            ],
        ),
    ]
