# Generated by Django 5.2.4 on 2025-09-17 14:59

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('unidades', '0031_alter_unidad_habit_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parqueadero',
            fields=[
                ('numero', models.CharField(max_length=5, primary_key=True, serialize=False, unique=True, validators=[django.core.validators.RegexValidator(message='El número del parqueadero debe contener entre 1 y 5 dígitos.', regex='^[0-9]{1,5}$')])),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de eliminación')),
                ('unidad_habit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parqueaderos', to='unidades.unidad_habit')),
            ],
            options={
                'verbose_name': 'Parqueadero',
                'verbose_name_plural': 'Parqueaderos',
                'db_table': 'parqueaderos_parqueadero',
                'ordering': ['unidad_habit', 'numero'],
                'constraints': [models.UniqueConstraint(fields=('numero', 'unidad_habit'), name='unique_numero_unidad_habit', violation_error_message='El número de parqueadero ya existe en esta unidad habitacional.')],
            },
        ),
    ]
