# Generated by Django 5.2.11 on 2026-03-15 23:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parqueaderos', '0001_initial'),
        ('unidades', '0034_alter_unidad_habit_piso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parqueadero',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='parqueadero',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='Fecha y hora en que el registro fue eliminado', null=True, verbose_name='Fecha de eliminación'),
        ),
        migrations.AlterField(
            model_name='parqueadero',
            name='unidad_habit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parqueaderos', to='unidades.unidad_habit'),
        ),
        migrations.AlterField(
            model_name='parqueadero',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Última actualización'),
        ),
    ]
