# Generated by Django 5.2.11 on 2026-03-16 14:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parqueaderos', '0002_alter_parqueadero_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parqueadero',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de creación'),
        ),
    ]
