# Generated by Django 5.2.4 on 2025-09-11 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('unidades', '0008_alter_division_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zona_social',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_zona', models.CharField(choices=[('G', 'Gimnasio'), ('S1', 'Salón Social_piso_1'), ('S2', 'Salón Social_piso_2'), ('ZB', 'Zona_BBQ')], max_length=4)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('capacidad', models.IntegerField(blank=True, null=True)),
                ('horario_disponible', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('unidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unidades.unidad')),
            ],
            options={
                'verbose_name': 'Zona Social',
                'verbose_name_plural': 'Zonas Sociales',
                'db_table': 'zona_social',
                'ordering': ['id'],
            },
        ),
    ]
