# Generated by Django 5.2.4 on 2025-09-11 17:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unidades', '0008_alter_division_unique_together'),
        ('zonas_sociales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zona_social',
            name='unidad',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='unidades.unidad'),
        ),
    ]
