# Generated by Django 5.2.4 on 2025-09-11 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zonas_sociales', '0002_alter_zona_social_unidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='zona_social',
            name='nombre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='zona_social',
            name='tipo_zona',
            field=models.CharField(choices=[('G', 'Gimnasio'), ('SS', 'Salón Social'), ('PS', 'Piscina'), ('ZB', 'Zona_BBQ'), ('CW', 'Zona_Coworking'), ('OO', 'Otro')], max_length=4),
        ),
    ]
