# Generated by Django 5.1.4 on 2025-09-16 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zonas_sociales', '0003_zona_social_nombre_alter_zona_social_tipo_zona'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zona_social',
            name='nombre',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre de la Zona'),
        ),
    ]
