# Generated by Django 5.1.4 on 2025-09-16 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zonas_sociales', '0004_alter_zona_social_nombre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zona_social',
            name='is_delete',
        ),
        migrations.AddField(
            model_name='zona_social',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de eliminación'),
        ),
        migrations.AddField(
            model_name='zona_social',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
