# Generated by Django 5.1.4 on 2025-09-16 20:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unidades', '0031_alter_unidad_habit_table'),
        ('zonas_sociales', '0005_remove_zona_social_is_delete_zona_social_deleted_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zona_social',
            name='unidad',
        ),
        migrations.AddField(
            model_name='zona_social',
            name='unidad_residencial',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='unidades.unidad', verbose_name='Unidad Residencial'),
        ),
    ]
