# Generated by Django 5.1.4 on 2025-09-16 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zonas_sociales', '0006_remove_zona_social_unidad_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='zona_social',
            table='zonas_sociales_zona_social',
        ),
    ]
