# Generated by Django 5.2.4 on 2025-09-17 20:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unidades', '0031_alter_unidad_habit_table'),
        ('zonas_sociales', '0007_alter_zona_social_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zona_social',
            name='unidad_residencial',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='zonas_sociales', to='unidades.unidad', verbose_name='Unidad Residencial'),
        ),
    ]
