# Generated by Django 5.2.11 on 2026-03-16 14:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zonas_sociales', '0008_alter_zona_social_unidad_residencial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zona_social',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='zona_social',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='Fecha y hora en que el registro fue eliminado', null=True, verbose_name='Fecha de eliminación'),
        ),
        migrations.AlterField(
            model_name='zona_social',
            name='horario_disponible',
            field=models.CharField(blank=True, help_text='Ej: Lunes a Viernes 8am-8pm', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='zona_social',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Última actualización'),
        ),
    ]
